version: "3.8"

volumes:
  rabbitmq_data:

services:
####################################
# RabbitMQ: Message broker 
####################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: esd-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  #################################
  # booking - Simple microservice
  #################################
  booking:
      build: 
        dockerfile: booking.Dockerfile
      restart: always
      environment:
        dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/bookings
        PYTHONUNBUFFERED: 1
      ports:
        - "5000:5000"

    #################################
    # notification - Simple microservice
    #################################
  notification:
      build:   
        dockerfile: notification.Dockerfile
      restart: always
      environment:
        dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/bookings
        PYTHONUNBUFFERED: 1
      ports:
        - "5008:5008"

  ###############################################
  # booktest - Complex Microservice
  ###############################################
  booktest:
    build: 
      dockerfile: booktest.Dockerfile
    restart: always
    depends_on:
      - booking
      - patient
      - notification
    environment:
      # do i have to list out the links ?
      bookingURL: http://bookings:5000/bookings
      patientURL: http://patient:5051/patient
      notificationURL: http://notification:5008/notification
      PYTHONUNBUFFERED: 1
    ports:
      - "5055:5055"

  #################################
  # get_appointments - Simple microservice
  #################################
  get_appointments:
      build:
        dockerfile: get_appointments.Dockerfile
      restart: always
      environment:
        dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/patient_records
        PYTHONUNBUFFERED: 1
      ports:
        - "5010:5010"

  #################################
  # appointment - Simple microservice im high
  #################################
  # appointment:
  #     build: 
  #       context: ./
  #       dockerfile: appointment.dockerfile
  #     image: dockerid/appointment
  #     restart: always
  #     environment:
  #       dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/ESD_T1
  #       PYTHONUNBUFFERED: 1
  #     ports:
  #       - "5000:5000"

  #################################
  # Patient: The Patient microservice
  #################################
  patient:
    build:
      dockerfile: patient.Dockerfile
    container_name: patient
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/patient_records
      PYTHONUNBUFFERED: 1
    ports:
      - "5051:5051"

  #################################
  # Drug: The Drug microservice
  #################################
  prescription_check:
    build:
      dockerfile: drug.Dockerfile
    container_name: drug
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/inventory
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
  ###############################################
  # prescribe_med: The prescribe_medicine.py program
  ###############################################
  prescribe:  
    build:
      dockerfile: prescribe_medicine.Dockerfile
    container_name: prescribe
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/patient_records
      PYTHONUNBUFFERED: 1
    ports:
      - "5101:5101"
    depends_on:
      - patient
      - prescription_check
  
  ############################################################
  # inventory.py program #####################################
  ############################################################
  inventory:
    build:
      dockerfile: inventory.Dockerfile
    container_name: inventory
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/inventory
      PYTHONUNBUFFERED: 1
    ports:
      - "5211:5211"

  ############################################################
  # dispense_restock.py program ##############################
  ############################################################
  dispense_restock:
    build:
      dockerfile: dispense_restock.Dockerfile
    container_name: dispense_restock
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/inventory
      PYTHONUNBUFFERED: 1
    ports:
      - "5204:5204"
    depends_on:
      - patient
      - inventory
      - rabbitmq
